site_name: ReCoDE-DeepLearning-Best-Practices
repo_url: https://github.com/ImperialCollegeLondon/ReCoDE-DeepLearning-Best-Practices
site_url: https://imperialcollegelondon.github.io/ReCoDE-DeepLearning-Best-Practices/
edit_uri: tree/main/docs/
theme:
  name: material
  custom_dir: docs

  icon:
    logo: logos/iclogo
  favicon: assets/iclogo.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  # SPA behaviour
  features:
    - navigation.instant
    - navigation.top
    - toc.follow
    - content.code.annotate
nav:
  - Home: index.md
  - Quick Start: learning/QuickStart.md
  - Learning Modules:
      - Lightning: learning/Learning_about_lightning.ipynb
      - Hydra: learning/Learning_about_hydra.ipynb
      - Einops: learning/Learning_about_einops.ipynb
      - Starting a New Project: learning/Starting_a_new_project.md
      - Install as Package: learning/Install_as_package.md
      - Template Tricks: learning/Learn_template_tricks.md
      - Best Practices: learning/Additional_Best_Practices.md
plugins:
  - search
  - tags
  - mkdocs-jupyter
  - include-markdown

# Set settings for markdown extensions
markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
