defaults:
  # - model_checkpoint # Uncomment to save model_checkpoint
  - model_summary
  - rich_progress_bar
  - learning_rate_monitor
  - _self_

# model_checkpoint:
#   auto_insert_metric_name: False