# @package _global_

defaults:
  - _self_
  - datamodule: fashion_mnist_datamodule # choose datamodule with `test_dataloader()` for evaluation
  - model: classification_model
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "generate"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: null
config_path: null
image_path: null