_target_: src.models.components.nets.conv_net.ConvNet
in_channels: 1 # 1 channel for FashionMNIST
channel_sizes: [32, 64, 128] # n convolutional layers
output_size: 10 # 10 classes
hidden_size: 64 # for the fully connected layer

